ALTER TABLE baby ADD COLUMN longitude DECIMAL(10,6) NULL;
ALTER TABLE baby ADD COLUMN latitude DECIMAL(10,6) NULL;
ALTER TABLE baby ADD COLUMN show_location BIT(1) NULL;
ALTER TABLE visit ADD COLUMN distance DECIMAL(20,6) NULL;
